### PR TITLE
Handle connected wallet on the wrong network

### LINKED ISSUE #139: Push users to wallet connect modal when they are connected on an unsupported network
As part of #138, we discussed with @perpetuum7 that it would be ideal to push the user to the wallet connect modal to select a supported network, when they have a wallet on an unsupported network connected.

### PR DESCRIPTION
**Pull request by thal0x**
If a user has a wallet connected but is on the wrong network, display the connect wallet modal.

Closes #139

### CODE REVIEW

File: components/vaultView/VaultView.tsx [hunk 1]
```diff
@@ -176,8 +174,8 @@ const VaultView: FC = () => {
           <PositionCard
             contractCount={1}
             mock
-            exerciseAssetAddress="0xc778417E063141139Fce010982780140Aa0cD5Ab"
-            underlyingAssetAddress="0xc7AD46e0b8a400Bb3C915120d284AafbA8fc4735"
+            exerciseAssetAddress="0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6"
```
Comment (0xAlcibiades) [inline components/vaultView/VaultView.tsx:177]: Hard coding these seems bad, we should load them from our per network token list based key, because we are now changing these for the 4th time.

**Review by 0xAlcibiades — CHANGES_REQUESTED** [review]

**Review by 0xAlcibiades — APPROVED** [review]
